title: Inpyo Lee
description: Robotics & AI notes
markdown: kramdown
timezone: Asia/Seoul

collections:
  notes:
    output: true
    permalink: /notes/:name/
  research_feed:
    output: true
    permalink: /research-feed/:name/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note
  - scope:
      path: ""
      type: research_feed
    values:
      layout: feed_note
